name: Reusable Python Lint and Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd calculator_project
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          cd calculator_project
          pylint $(find . -name "*.py")

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tests
        run: |
          python -m unittest discover
