name: running-python-script
on: workflow_dispatch

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
    - name: using git repository cloning actions..
      uses: actions/checkout@v4

    - name: list all files
      run: |
        echo "listing files and folders.."
        ls -la
        echo "repo sucessfully clone4d.."
        
  run-python-script:
    runs-on: ubuntu-latest
    needs: clone-repo
    steps:
      - name: check python version..
        run: python3 --version
      - name: running-script
        run: |
          chmod 777  app/prime-number.py
          python3 app/prime-number.py
    
